import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import AdminLayout, { AdminPageHeader } from '@/Layouts/AdminLayout';
import { formatCurrency } from '@/lib/format';
import { Head, router } from '@inertiajs/react';

export default function Invoices({ invoices }) {
    const finalizeInvoice = (invoice) => {
        if (!window.confirm(`Finalize payment for ${invoice.patient_name}?`)) {
            return;
        }

        router.patch(route('admin.invoices.finalize', invoice.id), {}, { preserveScroll: true });
    };

    return (
        <AdminLayout>
            <Head title="Package Invoices" />
            <AdminPageHeader title="Package Invoices" subtitle="Process package invoices generated by doctors during consultation completion." />

            <Card>
                <CardHeader>
                    <CardTitle>Pending package invoices</CardTitle>
                    <CardDescription>Finalizing an invoice marks it paid and activates the package consultation credits for the registered patient.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    {invoices.length === 0 ? (
                        <p className="rounded-2xl border border-dashed border-slate-300 p-4 text-sm text-slate-500">No pending package invoices.</p>
                    ) : null}

                    {invoices.map((invoice) => (
                        <div key={invoice.id} className="rounded-2xl border border-slate-200 p-4">
                            <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                                <div>
                                    <p className="font-medium text-slate-900">{invoice.patient_name}</p>
                                    {invoice.patient_phone ? <p className="mt-1 text-sm text-slate-500">WhatsApp: {invoice.patient_phone}</p> : null}
                                    <p className="mt-1 text-sm text-slate-500">{invoice.order_id} · booking #{invoice.booking_id} · consultation #{invoice.consultation_id}</p>
                                    <p className="mt-1 text-xs text-slate-400">Created {invoice.created_at}</p>
                                </div>
                                <div className="text-sm lg:text-right">
                                    <p className="font-semibold text-slate-900">{formatCurrency(invoice.amount)}</p>
                                    <p className="text-slate-500">{invoice.package?.name ?? 'Package unavailable'}</p>
                                    <p className="text-slate-500">{invoice.package?.consultation_credits ?? 0} credits</p>
                                </div>
                            </div>

                            <div className="mt-4 flex flex-wrap items-center gap-3">
                                <Button type="button" disabled={!invoice.can_finalize} onClick={() => finalizeInvoice(invoice)}>
                                    Finalize payment
                                </Button>
                                {!invoice.can_finalize ? <p className="text-sm text-rose-600">A registered patient and active package are required before this invoice can be finalized.</p> : null}
                            </div>
                        </div>
                    ))}
                </CardContent>
            </Card>
        </AdminLayout>
    );
}
